schema_version = "1.0.58"

id = "fabex"
version = "1.0.58"
name = "Fabex CNC (formerly BlenderCAM)"
tagline = "G-code Generation Tools"
maintainer = "Alain Pelletier and Contributors"
type = "add-on"

website = "https://blendercam.com/"

tags = ["3D View", "Add Curve", "Add Mesh", "Import-Export", "Object"]

blender_version_min = "4.2.0"

license = [
  "SPDX:GPL-3.0-or-later",
]

copyright = [
  "2012-2024 Vilem Novak, Alain Pelletier & contributors",
]

[permissions]
files = "Import/export G-code files from/to disk"

# Optional: build settings.
# https://docs.blender.org/manual/en/dev/advanced/extensions/command_line_arguments.html#command-line-args-extension-build
# [build]
# paths_exclude_pattern = [
#   "__pycache__/",
#   "/.git/",
#   "/*.zip",
# ]
